jobs:
  linux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: 'cd ${{ github.workspace }}/jvmti/jvmti-build

        mvn package

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: lib
        path: jvmti/jvmti-build/target/classes/lib*
  mac:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: 'cd ${{ github.workspace }}/jvmti/jvmti-build

        mvn package

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: lib
        path: jvmti/jvmti-build/target/classes/lib*
  windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: 'cd ${{ github.workspace }}/jvmti/jvmti-build

        mvn package

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: lib
        path: jvmti/jvmti-build/target/classes/*.dll
name: build jvmti
on:
  repository_dispatch:
    types: trigger-ga___build-jvmti.yml
